# Oathbound by Windyplains
# Basis from Freelancer by Taragoth & Caba'drin.

strings = [
	("oath_s21",									"{s21}"),
	("oath_denar",									"denar"),
	("oath_percent",								"percent"),
	("oath_file_event_log",							"Silverstag Oathbound Event Log"),
	("oath_reserved_05",							"reserved"),
	("oath_reserved_06",							"reserved"),
	("oath_reserved_07",							"reserved"),
	("oath_reserved_08",							"reserved"),
	("oath_reserved_09",							"reserved"),
	("oath_reserved_10",							"reserved"),
	("oath_reserved_11",							"reserved"),
	("oath_reserved_12",							"reserved"),
	("oath_reserved_13",							"reserved"),
	("oath_reserved_14",							"reserved"),
	("oath_reserved_15",							"reserved"),
	("oath_reserved_16",							"reserved"),
	("oath_reserved_17",							"reserved"),
	("oath_reserved_18",							"reserved"),
	("oath_reserved_19",							"reserved"),
	("oath_reserved_20",							"reserved"),
	("oath_reserved_21",							"reserved"),
	("oath_reserved_22",							"reserved"),
	("oath_reserved_23",							"reserved"),
	("oath_reserved_24",							"reserved"),
	("oath_reserved_25",							"reserved"),
	("oath_reserved_26",							"reserved"),
	("oath_reserved_27",							"reserved"),
	("oath_reserved_28",							"reserved"),
	("oath_reserved_29",							"reserved"),
	("oath_reserved_30",							"reserved"),
	
	("oath_quest_title",							"Oathbound Quest"),
	("oath_quest_s41_update_error",					"ERROR - Quest '{s41}' - Failed to update on function {reg31}."),
	("oath_quest_s41_update_note_error",			"ERROR - Quest '{s41}' - Failed to update quest note."),
	
	## QUEST TITLES
	("oath_quest_title_01",							"Desertion"),
	("oath_quest_title_02",							"Separation"),
	("oath_quest_title_03",							"Prisoners of War"),
	("oath_quest_title_04",							"Leave of Duty"),
	("oath_quest_title_05",							"The Butcher's Bill"),
	("oath_quest_title_06",							"The Sealed Letter"),
	("oath_quest_title_07",							"Courage Comes in Casks"),
	("oath_quest_title_08",							"Scouting Ahead"),
	("oath_quest_title_09",							"Only the Finest"),
	("oath_quest_title_10",							"Make Your Mark"),
	("oath_quest_title_11",							"An Early Retirement"),
	("oath_quest_title_12",							"Debts of War"),
	("oath_quest_title_13",							"Fresh Meat"),
	("oath_quest_title_14",							"Back Into the Fold"),
	("oath_quest_title_15",							"A Toast to Your Health"),
	("oath_quest_title_16",							"Accidents Happen"),
	("oath_quest_title_17",							"My Dearest Regards"),
	("oath_quest_title_18",							"Exchange of Custody"),
	("oath_quest_title_19",							"Culling the Useless"),
	("oath_quest_title_20",							"Where the Wind Blows"),
	("oath_quest_title_21",							"A Matter of Honor"),
	("oath_quest_title_22",							"The Shield of Duty"),
	("oath_quest_title_23",							"Breaking Their Spirit"),
	("oath_quest_title_24",							"To the End"),
	("oath_quest_title_25",							"Lessons of Necessity"),
	("oath_quest_title_26",							"Oaths That Bind"),
	("oath_quest_title_27",							"reserved"),
	("oath_quest_title_28",							"reserved"),
	("oath_quest_title_29",							"reserved"),
	("oath_quest_title_30",							"reserved"),
	
	## QUEST DESCRIPTIONS
	("oath_quest_desc_01",							"Desertion"),
	("oath_quest_desc_02",							"Separation"),
	("oath_quest_desc_03",							"Our lord needs men to gather 30 prisoners of war for a future exchange.  These enemies will need to be incapacitated with a blunt weapon to ensure they are merely wounded."),
	("oath_quest_desc_04",							"Leave of Duty"),
	("oath_quest_desc_05",							"Our lord requires several head of cattle to be purchased and brought back to the army for the men.  You will be supplied with sufficient coin and be expected back within a period of 30 days."),
	("oath_quest_desc_06",							"Our lord has need of a messenger who can discretely carry a letter to one of his peers and return with a reply.  You will be expected back within 30 days."),
	("oath_quest_desc_07",							"The quartermaster has need of someone to purchase several casks of ale to resupply the army's stock.  You will be expected back within 20 days."),
	("oath_quest_desc_08",							"Our lord has need of riders to scout ahead of our path, looking for suitable camp sites as well as keeping an eye towards enemy ambushes.  You will be expected back within 15 days."),
	("oath_quest_desc_09",							"Our lord has need of a trustworthy rider to have something commissioned for him at the nearest blacksmith of suitable skill.  Once you have placed the order you may return until it is ready or remain in the area."),
	("oath_quest_desc_10",							"Our lord is in need of more men.  Someone is needed to travel among the nearby settlements looking for fresh recruits and bring them back within the next 15 days."),
	("oath_quest_desc_11",							"An Early Retirement"),
	("oath_quest_desc_12",							"Debts of War"),
	("oath_quest_desc_13",							"Several of our latest recruits are just simple farmers, while they may know how to handle a pitchfork, proper soldiering is lost on them.  Our lord needs a competent trainer with a little experience to teach them the basics in combat."),
	("oath_quest_desc_14",							"Back Into the Fold"),
	("oath_quest_desc_15",							"A Toast to Your Health"),
	("oath_quest_desc_16",							"Accidents Happen"),
	("oath_quest_desc_17",							"My Dearest Regards"),
	("oath_quest_desc_18",							"Exchange of Custody"),
	("oath_quest_desc_19",							"Culling the Useless"),
	("oath_quest_desc_20",							"Where the Wind Blows"),
	("oath_quest_desc_21",							"A Matter of Honor"),
	("oath_quest_desc_22",							"The Shield of Duty"),
	("oath_quest_desc_23",							"Breaking Their Spirit"),
	("oath_quest_desc_24",							"To the End"),
	("oath_quest_desc_25",							"Lessons of Necessity"),
	("oath_quest_desc_26",							"Oaths That Bind"),
	("oath_quest_desc_27",							"reserved"),
	("oath_quest_desc_28",							"reserved"),
	("oath_quest_desc_29",							"reserved"),
	("oath_quest_desc_30",							"reserved"),
	
	## QUEST TYPES
	("oath_quest_type_01",							"Functional"),
	("oath_quest_type_02",							"Functional"),
	("oath_quest_type_03",							"In Party"),
	("oath_quest_type_04",							"Functional"),
	("oath_quest_type_05",							"Mission"),
	("oath_quest_type_06",							"Mission"),
	("oath_quest_type_07",							"Mission"),
	("oath_quest_type_08",							"Mission"),
	("oath_quest_type_09",							"Mission"),
	("oath_quest_type_10",							"Mission"),
	("oath_quest_type_11",							"Mission"),
	("oath_quest_type_12",							"Mission"),
	("oath_quest_type_13",							"In Party"),
	("oath_quest_type_14",							"Mission"),
	("oath_quest_type_15",							"Mission"),
	("oath_quest_type_16",							"Mission"),
	("oath_quest_type_17",							"Mission"),
	("oath_quest_type_18",							"Mission"),
	("oath_quest_type_19",							"Mission"),
	("oath_quest_type_20",							"Functional"),
	("oath_quest_type_21",							"Mission"),
	("oath_quest_type_22",							"In Party"),
	("oath_quest_type_23",							"In Party"),
	("oath_quest_type_24",							"Mission"),
	("oath_quest_type_25",							"In Party"),
	("oath_quest_type_26",							"Functional"),
	("oath_quest_type_27",							"reserved"),
	("oath_quest_type_28",							"reserved"),
	("oath_quest_type_29",							"reserved"),
	("oath_quest_type_30",							"reserved"),
	
	## QUEST SHORT DESC
	("oath_quest_short_desc_01",					"N/A"),
	("oath_quest_short_desc_02",					"N/A"),
	("oath_quest_short_desc_03",					"You have been charged with capturing prisoners. (Prisoners of War)"),
	("oath_quest_short_desc_04",					"N/A"),
	("oath_quest_short_desc_05",					"You have been tasked with bringing back cattle. (The Butcher's Bill)"),
	("oath_quest_short_desc_06",					"You have orders to deliver a message. (The Sealed Letter)"),
	("oath_quest_short_desc_07",					"You have been sent to purchase casks of ale. (Courage Comes in Casks)"),
	("oath_quest_short_desc_08",					"You have been given orders to scout ahead of the army's path. (Scouting Ahead)"),
	("oath_quest_short_desc_09",					"You have been tasked with commissioning an item. (Only The Finest)"),
	("oath_quest_short_desc_10",					"You have orders to gather several new recruits. (Make Your Mark)"),
	("oath_quest_short_desc_11",					"Mission"),
	("oath_quest_short_desc_12",					"Mission"),
	("oath_quest_short_desc_13",					"You have been tasked with training some of our new recruits. (Fresh Meat)"),
	("oath_quest_short_desc_14",					"Mission"),
	("oath_quest_short_desc_15",					"Mission"),
	("oath_quest_short_desc_16",					"Mission"),
	("oath_quest_short_desc_17",					"Mission"),
	("oath_quest_short_desc_18",					"Mission"),
	("oath_quest_short_desc_19",					"Mission"),
	("oath_quest_short_desc_20",					"N/A"),
	("oath_quest_short_desc_21",					"Mission"),
	("oath_quest_short_desc_22",					"In Party"),
	("oath_quest_short_desc_23",					"In Party"),
	("oath_quest_short_desc_24",					"Mission"),
	("oath_quest_short_desc_25",					"In Party"),
	("oath_quest_short_desc_26",					"N/A"),
	("oath_quest_short_desc_27",					"reserved"),
	("oath_quest_short_desc_28",					"reserved"),
	("oath_quest_short_desc_29",					"reserved"),
	("oath_quest_short_desc_30",					"reserved"),
]

from util_common import *

def modmerge_strings(orig_strings):
    # add remaining strings
    from util_common import add_objects
    num_appended, num_replaced, num_ignored = add_objects(orig_strings, strings)
    #print num_appended, num_replaced, num_ignored
	
	
# Used by modmerger framework version >= 200 to merge stuff
# This function will be looked for and called by modmerger if this mod is active
# Do not rename the function, though you can insert your own merging calls where indicated
def modmerge(var_set):
    try:
        var_name_1 = "strings"
        orig_strings = var_set[var_name_1]
        modmerge_strings(orig_strings)
    except KeyError:
        errstring = "Variable set does not contain expected variable: \"%s\"." % var_name_1
        raise ValueError(errstring)